"""Performance: the dashboard at volume, and the query plans that keep it there.

Phase 10's named failure mode is "slow queries at volume". A dashboard that is instant on the
twelve samples a developer has and unusable on the hundred thousand a user accumulates has not
been tested; it has been demonstrated.

So this file does two different things, and both matter:

* **A budget.** Building the dashboard over 100 000 stored samples completes inside spec §15's
  allowance. A wall-clock budget is machine-dependent, which is why these tests carry the
  ``performance`` marker and run nightly rather than in the pull-request gate — but a budget that
  is never asserted is a budget nobody notices breaking.
* **A plan.** The budget can be met by accident on a fast disk while the query is doing a full
  scan that will not survive the next order of magnitude. ``EXPLAIN QUERY PLAN`` is asserted
  directly: the dashboard's own statements must use the indexes the schema declares, and must not
  scan ``samples`` at all — the dashboard reads aggregates, and a dashboard that touched the
  sample table would be re-deriving figures the run engine already computed.

The volume is generated by inserting rows directly rather than by executing runs. That is
deliberate: this measures the *reading* path, and spending eight minutes of fake generation to
populate it would measure the run engine instead.
"""

from __future__ import annotations

import time
from collections.abc import Iterator
from datetime import timedelta
from pathlib import Path
from typing import Any

import pytest
from sqlalchemy import text

from freeweight.infrastructure.db.engine import create_engine_for
from freeweight.infrastructure.db.migration import MigrationRunner
from freeweight.services.database import MIGRATIONS_LOCATION, Database
from freeweight.services.results import (
    DashboardFilter,
    ResultsQuery,
    build_dashboard,
    query_results,
)

pytestmark = pytest.mark.performance

RUNS = 40
TESTS_PER_RUN = 5
SAMPLES_PER_TEST = 500
TOTAL_SAMPLES = RUNS * TESTS_PER_RUN * SAMPLES_PER_TEST  # 100 000

DASHBOARD_BUDGET_SECONDS = 2.0
"""What building the whole dashboard over 100 000 samples may take.

Generous on purpose: the assertion that matters is the query plan below, and a tight wall-clock
bound on shared CI hardware produces flakes rather than information."""

QUERY_BUDGET_SECONDS = 1.0
"""What one page of the metric-level query may take at the same volume."""

EXPORT_BUDGET_SECONDS = 10.0
"""What exporting one 10 000-sample run, samples and prompts included, may take (spec §15)."""

FIRST_CHUNK_BUDGET_SECONDS = 1.0
"""How long the first byte of a whole-database export may take.

The budget that matters for streaming: it must not grow with how much has been measured, because
the whole point is that the document leaves the process before it is finished."""


def _bulk_load(database: Database) -> None:
    """Insert a realistic shape of rows: many samples, fewer metrics, a handful of runs.

    Written as executemany against the mapped tables rather than through the ORM: the ORM would
    spend the test's whole budget on identity-map bookkeeping for rows nothing here reads back
    through it.
    """
    from freeweight.infrastructure.db.base import utcnow

    now = utcnow()
    with database.write() as session:
        session.execute(
            text(
                "INSERT INTO machines (id, machine_fingerprint, hostname, first_seen_at, "
                "last_seen_at) VALUES (:id, :fp, :host, :now, :now)"
            ),
            {"id": "01" + "M" * 24, "fp": "fp-bulk", "host": "bench", "now": now},
        )
        session.execute(
            text(
                "INSERT INTO models (id, provider_kind, provider_model_name, canonical_id, "
                "identity_confidence, first_seen_at, last_seen_at) VALUES (:id, 'fake', :name, "
                ":canonical, 'name_only', :now, :now)"
            ),
            [
                {
                    "id": f"01MODEL{index:019d}",
                    "name": f"bulk-{index}",
                    # A canonical ID is a pure function of the identity triple (ADR-0024),
                    # and the export validates it: a fixture that made one up would fail there
                    # rather than in the code under test.
                    "canonical": f"fake/bulk-{index}@unknown",
                    "now": now,
                }
                for index in range(4)
            ],
        )
        session.execute(
            text(
                "INSERT INTO model_descriptors (id, model_id, observed_at, descriptor_hash) "
                "VALUES (:id, :model, :now, :hash)"
            ),
            [
                {
                    "id": f"01DESC{index:020d}",
                    "model": f"01MODEL{index:019d}",
                    "now": now,
                    "hash": f"sha256:{index:064d}",
                }
                for index in range(4)
            ],
        )
        # The profile hash is recomputed from the profile's own fields on export (ADR-0023), so
        # the fixture takes it from the same function rather than inventing one.
        from baseaicore import RuntimeProfile

        session.execute(
            text(
                "INSERT INTO runtime_profiles (id, profile_hash, created_at) "
                "VALUES (:id, :hash, :now)"
            ),
            {"id": "01" + "P" * 24, "hash": RuntimeProfile().profile_hash, "now": now},
        )
        session.execute(
            text(
                "INSERT INTO benchmark_suites (id, key, name, version, runner, manifest_hash, "
                "installed_at) VALUES (:id, :key, :key, '1.0.0', 'native', :hash, :now)"
            ),
            [
                {
                    "id": f"01SUITE{index:019d}",
                    "key": f"native.bulk{index}",
                    "hash": f"sha256:{index:064d}",
                    "now": now,
                }
                for index in range(5)
            ],
        )
        session.execute(
            text(
                "INSERT INTO benchmark_tests (id, suite_id, key, name, scorer) "
                "VALUES (:id, :suite, :key, :key, 'rule')"
            ),
            [
                {
                    "id": f"01TEST{index:020d}",
                    "suite": f"01SUITE{index % 5:019d}",
                    "key": f"bulk.test{index}",
                }
                for index in range(TESTS_PER_RUN * 5)
            ],
        )

        run_rows: list[dict[str, Any]] = []
        run_test_rows: list[dict[str, Any]] = []
        sample_rows: list[dict[str, Any]] = []
        metric_rows: list[dict[str, Any]] = []
        for run_index in range(RUNS):
            run_id = f"01RUN{run_index:021d}"
            run_rows.append(
                {
                    "id": run_id,
                    "machine": "01" + "M" * 24,
                    "model": f"01MODEL{run_index % 4:019d}",
                    "descriptor": f"01DESC{run_index % 4:020d}",
                    "profile": "01" + "P" * 24,
                    "suite": f"01SUITE{run_index % 5:019d}",
                    "created": now - timedelta(minutes=run_index),
                    "fingerprint": f"sha256:{run_index:064d}",
                }
            )
            for test_index in range(TESTS_PER_RUN):
                run_test_id = f"01RT{run_index:011d}{test_index:011d}"
                run_test_rows.append(
                    {
                        "id": run_test_id,
                        "run": run_id,
                        "test": f"01TEST{(run_index % 5) * TESTS_PER_RUN + test_index:020d}",
                    }
                )
                sample_rows.extend(
                    {
                        "id": f"01S{run_index:07d}{test_index:07d}{sample_index:09d}",
                        "run_test": run_test_id,
                        "case": f"case-{sample_index}",
                        "ordinal": sample_index,
                        "score": (sample_index % 10) / 10,
                        "created": now,
                    }
                    for sample_index in range(SAMPLES_PER_TEST)
                )
                metric_rows.append(
                    {
                        "id": f"01MV{run_index:011d}{test_index:011d}",
                        "run": run_id,
                        "run_test": run_test_id,
                        "key": "task_success",
                        "value": 0.5 + (test_index / 100),
                        "created": now,
                    }
                )
            metric_rows.append(
                {
                    "id": f"01MVRUN{run_index:019d}",
                    "run": run_id,
                    "run_test": None,
                    "key": "task_success",
                    "value": 0.5,
                    "created": now,
                }
            )

        session.execute(
            text(
                "INSERT INTO runs (id, machine_id, model_id, model_descriptor_id, "
                "runtime_profile_id, suite_id, status, created_at, completed_at, "
                "reproducibility_fingerprint, multi_gpu_visible) VALUES (:id, :machine, :model, "
                ":descriptor, :profile, :suite, 'completed', :created, :created, :fingerprint, 0)"
            ),
            run_rows,
        )
        session.execute(
            text(
                "INSERT INTO run_tests (id, run_id, test_id, status, completed_cases, "
                "total_cases, repetitions, measurement_class) VALUES (:id, :run, :test, "
                "'completed', 0, 0, 1, 'warm')"
            ),
            run_test_rows,
        )
        for start in range(0, len(sample_rows), 5000):
            session.execute(
                text(
                    "INSERT INTO samples (id, run_test_id, case_id, ordinal, repetition, status, "
                    "score, created_at) VALUES (:id, :run_test, :case, :ordinal, 1, 'completed', "
                    ":score, :created)"
                ),
                sample_rows[start : start + 5000],
            )
        session.execute(
            text(
                "INSERT INTO metric_values (id, run_id, run_test_id, metric_key, numeric_value, "
                "unit, aggregation, higher_is_better, sample_count, excluded_count, created_at) "
                "VALUES (:id, :run, :run_test, :key, :value, 'ratio', 'mean', 1, 500, 0, :created)"
            ),
            metric_rows,
        )


@pytest.fixture(scope="module")
def loaded(tmp_path_factory: pytest.TempPathFactory) -> Iterator[Database]:
    """A database holding 100 000 samples, built once for the whole module."""
    root: Path = tmp_path_factory.mktemp("dashboard-perf")
    url = f"sqlite:///{root / 'freeweight.sqlite3'}"
    engine = create_engine_for(url)
    try:
        MigrationRunner(engine, script_location=MIGRATIONS_LOCATION).upgrade(backup=False)
    finally:
        engine.dispose()
    database = Database.from_url(url)
    _bulk_load(database)
    with database.write() as session:
        session.execute(text("ANALYZE"))
    try:
        yield database
    finally:
        database.close()


def _plan(database: Database, statement: str, parameters: dict[str, Any]) -> str:
    """The SQLite query plan for one statement, as one lower-case string."""
    with database.read() as session:
        rows = session.execute(text(f"EXPLAIN QUERY PLAN {statement}"), parameters).all()
    return " | ".join(str(row[-1]) for row in rows).lower()


class TestTheVolumeIsReal:
    def test_the_fixture_holds_a_hundred_thousand_samples(self, loaded: Database) -> None:
        with loaded.read() as session:
            samples = session.execute(text("SELECT count(*) FROM samples")).scalar_one()

        assert samples == TOTAL_SAMPLES


class TestBudgets:
    def test_the_dashboard_builds_within_budget(self, loaded: Database) -> None:
        start = time.perf_counter()
        dashboard = build_dashboard(loaded, DashboardFilter())
        elapsed = time.perf_counter() - start

        assert dashboard.cards.completed_runs == RUNS
        assert dashboard.cards.samples_stored == TOTAL_SAMPLES
        assert elapsed < DASHBOARD_BUDGET_SECONDS, f"dashboard took {elapsed:.2f}s"

    def test_one_page_of_the_metric_query_is_within_budget(self, loaded: Database) -> None:
        start = time.perf_counter()
        page = query_results(loaded, ResultsQuery(limit=50))
        elapsed = time.perf_counter() - start

        assert len(page.rows) == 50  # noqa: PLR2004 — the requested page size
        assert elapsed < QUERY_BUDGET_SECONDS, f"one page took {elapsed:.2f}s"

    def test_a_filtered_query_is_not_slower_than_an_unfiltered_one(self, loaded: Database) -> None:
        """A filter that forced a scan would make the dashboard's own filters a trap."""
        start = time.perf_counter()
        query_results(loaded, ResultsQuery(suite="native.bulk1", limit=50))
        elapsed = time.perf_counter() - start

        assert elapsed < QUERY_BUDGET_SECONDS, f"a filtered page took {elapsed:.2f}s"


class TestExportBudget:
    """Phase 10 acceptance criterion 4: exports stream a 10 000-sample run within budget."""

    def test_a_ten_thousand_sample_run_exports_within_budget(self, loaded: Database) -> None:
        from freeweight.services.export import ExportScope, ExportSelection, iter_export

        run_id = f"01RUN{0:021d}"
        selection = ExportSelection(
            scope=ExportScope.RUN, selector=run_id, include_samples=True, include_prompts=True
        )

        start = time.perf_counter()
        size = sum(len(chunk) for chunk in iter_export(loaded, selection))
        elapsed = time.perf_counter() - start

        assert size > 0
        assert elapsed < EXPORT_BUDGET_SECONDS, f"the export took {elapsed:.2f}s"

    def test_the_first_chunk_leaves_before_the_samples_are_read(self, loaded: Database) -> None:
        """Streaming is the property that makes the budget a design fact rather than luck."""
        from freeweight.services.export import ExportScope, ExportSelection, iter_export

        selection = ExportSelection(
            scope=ExportScope.ALL, include_samples=True, include_prompts=True
        )
        stream = iter(iter_export(loaded, selection))

        start = time.perf_counter()
        first = next(stream)
        elapsed = time.perf_counter() - start

        assert first.startswith('{"generated_at":')
        assert elapsed < FIRST_CHUNK_BUDGET_SECONDS, f"the first chunk took {elapsed:.2f}s"

    def test_the_csv_form_streams_one_row_per_metric(self, loaded: Database) -> None:
        from freeweight.services.export import (
            ExportFormat,
            ExportScope,
            ExportSelection,
            iter_export,
        )

        selection = ExportSelection(scope=ExportScope.ALL, export_format=ExportFormat.CSV)

        start = time.perf_counter()
        rows = sum(1 for _ in iter_export(loaded, selection))
        elapsed = time.perf_counter() - start

        # One header, then one row per metric row across every run.
        assert rows == 1 + RUNS * (TESTS_PER_RUN + 1)
        assert elapsed < EXPORT_BUDGET_SECONDS, f"the CSV export took {elapsed:.2f}s"


class TestQueryPlans:
    def test_the_metric_query_never_scans_the_sample_table(self, loaded: Database) -> None:
        """The dashboard reads aggregates. Touching ``samples`` would mean re-deriving them."""
        plan = _plan(
            loaded,
            "SELECT mv.id FROM metric_values mv JOIN runs r ON r.id = mv.run_id "
            "WHERE mv.sample_id IS NULL AND r.status = :status "
            "ORDER BY r.created_at DESC, r.id DESC, mv.metric_key ASC, mv.id ASC LIMIT 51",
            {"status": "completed"},
        )

        assert "samples" not in plan, plan

    def test_the_run_join_uses_the_primary_key_rather_than_a_scan(self, loaded: Database) -> None:
        plan = _plan(
            loaded,
            "SELECT mv.id FROM metric_values mv JOIN runs r ON r.id = mv.run_id "
            "WHERE mv.run_id = :run",
            {"run": f"01RUN{0:021d}"},
        )

        assert "scan runs" not in plan, plan

    def test_the_metric_lookup_for_one_run_uses_its_index(self, loaded: Database) -> None:
        """``metric_values`` is the widest table the dashboard reads; it must not be scanned."""
        plan = _plan(
            loaded,
            "SELECT id FROM metric_values WHERE run_id = :run AND sample_id IS NULL",
            {"run": f"01RUN{0:021d}"},
        )

        assert "scan metric_values" not in plan, plan

    def test_the_sample_count_card_uses_the_run_test_index(self, loaded: Database) -> None:
        """The one card that does count samples must reach them through ``run_tests``."""
        plan = _plan(
            loaded,
            "SELECT count(*) FROM samples s JOIN run_tests rt ON rt.id = s.run_test_id "
            "WHERE rt.run_id = :run",
            {"run": f"01RUN{0:021d}"},
        )

        assert "scan samples" not in plan, plan
